version: "3.6"
services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.0.1.cli-migrations-v3
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    # extra_hosts:
    # - "host.docker.internal:host-gateway"
    depends_on:
      - "postgres"
    restart: always
    # volumes:
    #   - ./hasura/migrations:/hasura-migrations
    #   - ./hasura/metadata:/hasura-metadata
    # volumes:
    #   - ./migrations:/hasura_migrations #i have created this hasura_migration volume
    #   - ./metadata:/hasura_metadata #i have created this hasura_metadata volume
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_JWT_SECRET: '{ "jwk_url": "https://dev-8d2odgqs85hwxmls.us.auth0.com/.well-known/jwks.json" }'
volumes:
  db_data:
